#ifndef _PENTAX_PTP_COMMANDS_H_
#define _PENTAX_PTP_COMMANDS_H_

#define PTP_VENDOR_PENTAX_BULB_MODE_START      0x0011
#define PTP_VENDOR_PENTAX_BULB_MODE_STOP       0x0012
#define PTP_VENDOR_PENTAX_MIRROR_UP_ENABLE     0x0013
#define PTP_VENDOR_PENTAX_MIRROR_UP_DISABLE    0x0014

#endif // _PENTAX_PTP_COMMANDS_H_
